POST http://localhost:3000/api/nfe/v1/ServiceInvoices/67ec429ea1a2cb0754e9f1f2/
Content-Type: application/json
Authorization: Bearer I1YqBVtMz3H1J2W1g4rQX7dGmUKOJpgspZY8J6dwjNHGidJnWUjAwJZZusyoAFnwmTW

{
  "borrower": {
    "type": "Undefined",
    "name": "Enrico Cidade Blanco",
    "federalTaxNumber": 46121891000135,
    "municipalTaxNumber": "string",
    "taxRegime": "Isento",
    "email": "enrico.blanco@cathalyst.com.br",
    "address": {
      "country": "BRA",
      "postalCode": "90570145",
      "street": "Rua Coronel Bordini",
      "number": "187",
      "additionalInformation": "12",
      "district": "Moinhos de Vento",
      "city": {
        "code": "4314902",
        "name": "Porto Alegre"
      },
      "state": "RS"
    }
  },
  "externalId": "enrico",
  "cityServiceCode": "string",
  "federalServiceCode": "string",
  "cnaeCode": "string",
  "description": "string",
  "servicesAmount": 0,
  "rpsSerialNumber": "string",
  "issuedOn": "2025-04-01T19:23:09.528Z",
  "rpsNumber": 10,
  "taxationType": "None",
  "issRate": 0,
  "issTaxAmount": 0,
  "deductionsAmount": 0,
  "discountUnconditionedAmount": 0,
  "discountConditionedAmount": 0,
  "irAmountWithheld": 0,
  "pisAmountWithheld": 0,
  "cofinsAmountWithheld": 0,
  "csllAmountWithheld": 0,
  "inssAmountWithheld": 0,
  "issAmountWithheld": 0,
  "othersAmountWithheld": 0,
  "approximateTax": {
    "source": "string",
    "version": "string",
    "totalRate": 0
  },
  "additionalInformation": "string",
  "location": {
    "state": "RS",
    "country": "BRA",
    "postalCode": "90570145",
    "street": "Rua Coronel Bordini",
    "number": "187",
    "district": "Moinhos de Vento",
    "additionalInformation": "12",
    "city": {
      "code": "4314902",
      "name": "Porto Alegre"
    }
  },
  "activityEvent": {
    "name": "string",
    "startOn": "2025-04-01T19:23:09.528Z",
    "endOn": "2025-04-01T19:23:09.528Z",
    "atvEvId": "string"
  }
}

# {
#   "id": "123456",
#   "environment": "Development",
#   "flowStatus": "Issued",
#   "flowMessage": "Emissão bem-sucedida",
#   "provider": {
#     "id": "provider123",
#     "tradeName": "Empresa XYZ Ltda",
#     "openningDate": "2020-01-01",
#     "taxRegime": "SimplesNacional",
#     "specialTaxRegime": "Nenhum",
#     "legalNature": "SociedadeEmpresariaLimitada",
#     "economicActivities": [
#       {
#         "type": "Main",
#         "code": 6201500
#       }
#     ],
#     "companyRegistryNumber": 12345678,
#     "regionalTaxNumber": 987654321,
#     "municipalTaxNumber": "123456789",
#     "issRate": 0.04,
#     "federalTaxDetermination": "SimplesNacional",
#     "municipalTaxDetermination": "SimplesNacional",
#     "loginName": "usuarioxyz",
#     "loginPassword": "senha123",
#     "authIssueValue": "authkey123",
#     "name": "Fornecedor XYZ",
#     "federalTaxNumber": 12345678901234,
#     "email": "contato@fornecedorxyz.com.br",
#     "address": {
#       "country": "Brasil",
#       "postalCode": "90570145",
#       "street": "Rua X",
#       "number": "123",
#       "additionalInformation": "Sala 101",
#       "district": "Centro",
#       "city": {
#         "code": "4314902",
#         "name": "Porto Alegre",
#         "state": "RS"
#       }
#     },
#     "status": "Active",
#     "type": "LegalEntity",
#     "createdOn": "2023-01-01T00:00:00.000Z",
#     "modifiedOn": "2023-01-01T00:00:00.000Z"
#   },
#   "borrower": {
#     "parentId": "parent123",
#     "id": "borrower123",
#     "name": "Cliente ABC",
#     "federalTaxNumber": 98765432101234,
#     "email": "contato@clienteabc.com.br",
#     "address": {
#       "country": "Brasil",
#       "postalCode": "91060900",
#       "street": "Avenida Y",
#       "number": "456",
#       "additionalInformation": "Andar 10",
#       "district": "Bairro Z",
#       "city": {
#         "code": "4314902",
#         "name": "Porto Alegre",
#         "state": "RS"
#       }
#     }
#   },
#   "externalId": "ext-001",
#   "batchNumber": 1001,
#   "batchCheckNumber": "batch-001",
#   "number": 12345,
#   "checkCode": "check-12345",
#   "status": "Created",
#   "rpsType": "Rps",
#   "rpsStatus": "Normal",
#   "taxationType": "WithinCity",
#   "issuedOn": "2025-03-31T17:56:17.935Z",
#   "cancelledOn": "2025-03-31T17:56:17.935Z",
#   "rpsSerialNumber": "123456789",
#   "rpsNumber": 1,
#   "cityServiceCode": "CS123",
#   "federalServiceCode": "FS123",
#   "description": "Descrição do serviço prestado",
#   "servicesAmount": 1000,
#   "deductionsAmount": 100,
#   "discountUnconditionedAmount": 50,
#   "discountConditionedAmount": 30,
#   "baseTaxAmount": 820,
#   "issRate": 5,
#   "issTaxAmount": 41,
#   "irAmountWithheld": 10,
#   "pisAmountWithheld": 2,
#   "cofinsAmountWithheld": 3,
#   "csllAmountWithheld": 1,
#   "inssAmountWithheld": 5,
#   "issAmountWithheld": 41,
#   "othersAmountWithheld": 0,
#   "amountWithheld": 102,
#   "amountNet": 900,
#   "location": {
#     "state": "RS",
#     "country": "Brasil",
#     "postalCode": "90570145",
#     "street": "Rua X",
#     "number": "123",
#     "district": "Centro",
#     "additionalInformation": "",
#     "city": {
#       "code": "4314902",
#       "name": "Porto Alegre",
#       "state": "RS"
#     }
#   },
#   "activityEvent": {
#     "name": "Prestação de Serviço",
#     "startOn": "2025-03-31T17:56:17.935Z",
#     "endOn": "2025-03-31T17:56:17.935Z",
#     "atvEvId": "ev123"
#   },
#   "approximateTax": {
#     "source": "IBPT",
#     "version": "23.1.A",
#     "totalRate": 41
#   },
#   "additionalInformation": "Informações adicionais sobre o serviço",
#   "createdOn": "2025-03-31T17:56:17.935Z",
#   "modifiedOn": "2025-03-31T17:56:17.935Z"
# }

# GET http://localhost:3000/api/nfe/v1/Companies
# Accept: application/json
# Content-Type: application/json
# Authorization: Bearer I1YqBVtMz3H1J2W1g4rQX7dGmUKOJpgspZY8J6dwjNHGidJnWUjAwJZZusyoAFnwmTW

# DELETE http://localhost:3000/api/nfe/v1/Companies/67ec421cf2f80c11b4cb8ee3
# Accept: application/json
# Content-Type: application/json
# Authorization: Bearer a8VfVsnvIk5NnOdMmOELTb3LzJ8g5bnrq6SlxuattllicSOBxPSVD4qlaZpbTjekJIn


# POST http://localhost:3000/api/nfe/v1/Companies
# Accept: application/json
# Content-Type: application/json
# Authorization: Bearer I1YqBVtMz3H1J2W1g4rQX7dGmUKOJpgspZY8J6dwjNHGidJnWUjAwJZZusyoAFnwmTW

# {
#   "id": "enrico",
#   "name": "Enrico Cidade Blanco",
#   "tradeName": "enrico",
#   "federalTaxNumber": 46121891000135,
#   "email": "enrico.blanco@cathalyst.com.br",
#   "address": {
#     "country": "Brazil",
#     "postalCode": "90570145",
#     "street": "Rua Coronel Bordini",
#     "number": "187 ",
#     "additionalInformation": "12",
#     "district": "Moinhos de Vento",
#     "city": {
#       "code": 4314902,
#       "name": "Porto Alegre"
#     },
#     "state": "RS"
#   },
#   "openningDate": "2025-04-01T18:22:50.115Z",
#   "taxRegime": "Isento",
#   "specialTaxRegime": "Automatico",
#   "legalNature": "Empresario",
#   "economicActivities": [
#     {
#       "type": "Main",
#       "code": 0
#     }
#   ],
#   "companyRegistryNumber": 0,
#   "regionalTaxNumber": 0,
#   "municipalTaxNumber": "string",
#   "rpsSerialNumber": "string",
#   "rpsNumber": 10,
#   "issRate": 0,
#   "environment": "Development",
#   "fiscalStatus": "CityNotSupported",
#   "federalTaxDetermination": "NotInformed",
#   "municipalTaxDetermination": "NotInformed",
#   "loginName": "string",
#   "loginPassword": "string",
#   "authIssueValue": "string",
#   "certificate": {
#     "thumbprint": "string",
#     "modifiedOn": "2025-04-01T18:22:50.115Z",
#     "expiresOn": "2025-04-01T18:22:50.115Z",
#     "status": "Overdue"
#   },
#   "createdOn": "2025-04-01T18:22:50.115Z",
#   "modifiedOn": "2025-04-01T18:22:50.115Z"
# }